// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthLoginData, AuthLoginErrors, AuthLoginResponses, AuthLogoutData, AuthLogoutErrors, AuthLogoutResponses, AuthMeData, AuthMeErrors, AuthMeResponses, AuthRefreshData, AuthRefreshErrors, AuthRefreshResponses, AuthSignupData, AuthSignupErrors, AuthSignupResponses, PlayersCreateData, PlayersCreateErrors, PlayersCreateResponses, PlayersDisableData, PlayersDisableErrors, PlayersDisableResponses, PlayersEnableData, PlayersEnableErrors, PlayersEnableResponses, PlayersGetData, PlayersGetErrors, PlayersGetResponses, PlayersListData, PlayersListErrors, PlayersListResponses, PlayersUpdateData, PlayersUpdateErrors, PlayersUpdateResponses, SportsCreateData, SportsCreateErrors, SportsCreateResponses, SportsDeleteData, SportsDeleteErrors, SportsDeleteResponses, SportsGetData, SportsGetErrors, SportsGetResponses, SportsListData, SportsListErrors, SportsListResponses, SportsUpdateData, SportsUpdateErrors, SportsUpdateResponses, TeamsCreateData, TeamsCreateErrors, TeamsCreateResponses, TeamsDisableData, TeamsDisableErrors, TeamsDisableResponses, TeamsEnableData, TeamsEnableErrors, TeamsEnableResponses, TeamsGetData, TeamsGetErrors, TeamsGetResponses, TeamsListData, TeamsListErrors, TeamsListResponses, TeamsUpdateData, TeamsUpdateErrors, TeamsUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Start an authenticated session
 *
 * Validates credentials and returns a 15-minute access token plus a rotating refresh token.
 */
export const authLogin = <ThrowOnError extends boolean = false>(options: Options<AuthLoginData, ThrowOnError>): RequestResult<AuthLoginResponses, AuthLoginErrors, ThrowOnError> => (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
  url: '/auth/login',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Revoke the current session
 *
 * Accepts either token type and revokes its persistent session.
 */
export const authLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthLogoutData, ThrowOnError>): RequestResult<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError> => (options?.client ?? client).delete<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }, {
      key: 'RefreshTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/auth/logout',
  ...options
});

/**
 * Get the authenticated user
 *
 * Requires a valid access token.
 */
export const authMe = <ThrowOnError extends boolean = false>(options?: Options<AuthMeData, ThrowOnError>): RequestResult<AuthMeResponses, AuthMeErrors, ThrowOnError> => (options?.client ?? client).get<AuthMeResponses, AuthMeErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/auth/me',
  ...options
});

/**
 * Rotate a refresh token
 *
 * Requires the current refresh token. It is invalidated and replaced with a new access/refresh pair; reuse revokes the whole session.
 */
export const authRefresh = <ThrowOnError extends boolean = false>(options?: Options<AuthRefreshData, ThrowOnError>): RequestResult<AuthRefreshResponses, AuthRefreshErrors, ThrowOnError> => (options?.client ?? client).post<AuthRefreshResponses, AuthRefreshErrors, ThrowOnError>({
  security: [{
      key: 'RefreshTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/auth/refresh',
  ...options
});

/**
 * Register a referee account
 *
 * Creates a public account with the referee role.
 */
export const authSignup = <ThrowOnError extends boolean = false>(options: Options<AuthSignupData, ThrowOnError>): RequestResult<AuthSignupResponses, AuthSignupErrors, ThrowOnError> => (options.client ?? client).post<AuthSignupResponses, AuthSignupErrors, ThrowOnError>({
  url: '/auth/signup',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * List Players
 *
 * Returns filtered, sorted, and paginated Players. Enabled Players are returned by default and pages contain at most 25 records.
 */
export const playersList = <ThrowOnError extends boolean = false>(options?: Options<PlayersListData, ThrowOnError>): RequestResult<PlayersListResponses, PlayersListErrors, ThrowOnError> => (options?.client ?? client).get<PlayersListResponses, PlayersListErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/players',
  ...options
});

/**
 * Create a Player
 *
 * Creates an enabled Player and up to three validated Team memberships atomically.
 */
export const playersCreate = <ThrowOnError extends boolean = false>(options: Options<PlayersCreateData, ThrowOnError>): RequestResult<PlayersCreateResponses, PlayersCreateErrors, ThrowOnError> => (options.client ?? client).post<PlayersCreateResponses, PlayersCreateErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/players',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Get a Player
 *
 * Returns one enabled or disabled Player by identifier.
 */
export const playersGet = <ThrowOnError extends boolean = false>(options: Options<PlayersGetData, ThrowOnError>): RequestResult<PlayersGetResponses, PlayersGetErrors, ThrowOnError> => (options.client ?? client).get<PlayersGetResponses, PlayersGetErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/players/{player_id}',
  ...options
});

/**
 * Update a Player
 *
 * Updates the name and atomically replaces all Team memberships of an enabled Player.
 */
export const playersUpdate = <ThrowOnError extends boolean = false>(options: Options<PlayersUpdateData, ThrowOnError>): RequestResult<PlayersUpdateResponses, PlayersUpdateErrors, ThrowOnError> => (options.client ?? client).put<PlayersUpdateResponses, PlayersUpdateErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/players/{player_id}',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Disable a Player
 *
 * Disables a Player and permanently removes all Team memberships. Repeated requests are idempotent.
 */
export const playersDisable = <ThrowOnError extends boolean = false>(options: Options<PlayersDisableData, ThrowOnError>): RequestResult<PlayersDisableResponses, PlayersDisableErrors, ThrowOnError> => (options.client ?? client).patch<PlayersDisableResponses, PlayersDisableErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/players/{player_id}/disable',
  ...options
});

/**
 * Enable a Player
 *
 * Enables a Player without restoring prior Team memberships. Repeated requests are idempotent.
 */
export const playersEnable = <ThrowOnError extends boolean = false>(options: Options<PlayersEnableData, ThrowOnError>): RequestResult<PlayersEnableResponses, PlayersEnableErrors, ThrowOnError> => (options.client ?? client).patch<PlayersEnableResponses, PlayersEnableErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/players/{player_id}/enable',
  ...options
});

/**
 * List sports
 *
 * Returns every sport ordered by identifier.
 */
export const sportsList = <ThrowOnError extends boolean = false>(options?: Options<SportsListData, ThrowOnError>): RequestResult<SportsListResponses, SportsListErrors, ThrowOnError> => (options?.client ?? client).get<SportsListResponses, SportsListErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/sports',
  ...options
});

/**
 * Create a sport
 *
 * Creates a uniquely normalized Sport. max_players is the Team pool capacity and max_players_in_game is the simultaneous lineup limit.
 */
export const sportsCreate = <ThrowOnError extends boolean = false>(options: Options<SportsCreateData, ThrowOnError>): RequestResult<SportsCreateResponses, SportsCreateErrors, ThrowOnError> => (options.client ?? client).post<SportsCreateResponses, SportsCreateErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/sports',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Delete a sport
 *
 * Deletes one Sport only when no enabled or disabled Team or Player references it.
 */
export const sportsDelete = <ThrowOnError extends boolean = false>(options: Options<SportsDeleteData, ThrowOnError>): RequestResult<SportsDeleteResponses, SportsDeleteErrors, ThrowOnError> => (options.client ?? client).delete<SportsDeleteResponses, SportsDeleteErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/sports/{sport_id}',
  ...options
});

/**
 * Get a sport
 *
 * Returns one sport by identifier.
 */
export const sportsGet = <ThrowOnError extends boolean = false>(options: Options<SportsGetData, ThrowOnError>): RequestResult<SportsGetResponses, SportsGetErrors, ThrowOnError> => (options.client ?? client).get<SportsGetResponses, SportsGetErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/sports/{sport_id}',
  ...options
});

/**
 * Rename a sport
 *
 * Changes only the Sport name; both capacity fields are immutable.
 */
export const sportsUpdate = <ThrowOnError extends boolean = false>(options: Options<SportsUpdateData, ThrowOnError>): RequestResult<SportsUpdateResponses, SportsUpdateErrors, ThrowOnError> => (options.client ?? client).put<SportsUpdateResponses, SportsUpdateErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/sports/{sport_id}',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * List Teams
 *
 * Returns a filtered and paginated Team catalogue. Enabled Teams are returned by default and each page contains at most 25 records.
 */
export const teamsList = <ThrowOnError extends boolean = false>(options?: Options<TeamsListData, ThrowOnError>): RequestResult<TeamsListResponses, TeamsListErrors, ThrowOnError> => (options?.client ?? client).get<TeamsListResponses, TeamsListErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/teams',
  ...options
});

/**
 * Create a Team
 *
 * Creates an enabled Team. Its identity is unique by normalized name, Sport, and gender category.
 */
export const teamsCreate = <ThrowOnError extends boolean = false>(options: Options<TeamsCreateData, ThrowOnError>): RequestResult<TeamsCreateResponses, TeamsCreateErrors, ThrowOnError> => (options.client ?? client).post<TeamsCreateResponses, TeamsCreateErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/teams',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Get a Team
 *
 * Returns one enabled or disabled Team by identifier.
 */
export const teamsGet = <ThrowOnError extends boolean = false>(options: Options<TeamsGetData, ThrowOnError>): RequestResult<TeamsGetResponses, TeamsGetErrors, ThrowOnError> => (options.client ?? client).get<TeamsGetResponses, TeamsGetErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/teams/{team_id}',
  ...options
});

/**
 * Rename a Team
 *
 * Changes only the name of an enabled Team. Sport and gender are immutable.
 */
export const teamsUpdate = <ThrowOnError extends boolean = false>(options: Options<TeamsUpdateData, ThrowOnError>): RequestResult<TeamsUpdateResponses, TeamsUpdateErrors, ThrowOnError> => (options.client ?? client).put<TeamsUpdateResponses, TeamsUpdateErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/teams/{team_id}',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

/**
 * Disable a Team
 *
 * Disables a Team and removes its Player memberships without deleting it. Repeated requests are idempotent.
 */
export const teamsDisable = <ThrowOnError extends boolean = false>(options: Options<TeamsDisableData, ThrowOnError>): RequestResult<TeamsDisableResponses, TeamsDisableErrors, ThrowOnError> => (options.client ?? client).patch<TeamsDisableResponses, TeamsDisableErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/teams/{team_id}/disable',
  ...options
});

/**
 * Enable a Team
 *
 * Enables a Team without restoring prior Player memberships. Repeated requests are idempotent.
 */
export const teamsEnable = <ThrowOnError extends boolean = false>(options: Options<TeamsEnableData, ThrowOnError>): RequestResult<TeamsEnableResponses, TeamsEnableErrors, ThrowOnError> => (options.client ?? client).patch<TeamsEnableResponses, TeamsEnableErrors, ThrowOnError>({
  security: [{
      key: 'AccessTokenAuth',
      scheme: 'bearer',
      type: 'http'
    }],
  url: '/teams/{team_id}/enable',
  ...options
});
