// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://127.0.0.1:5000' | (string & {});
};

/**
 * ErrorBody
 */
export type ErrorBody = {
  /**
   * Code
   */
  code: string;
  /**
   * Details
   */
  details?: Array<ValidationDetail> | null;
  /**
   * Message
   */
  message: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
  error: ErrorBody;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
  /**
   * Email
   */
  email: string;
};

/**
 * PaginationResponse
 */
export type PaginationResponse = {
  /**
   * Page
   */
  page: number;
  /**
   * Per Page
   */
  per_page: number;
  /**
   * Total Items
   */
  total_items: number;
  /**
   * Total Pages
   */
  total_pages: number;
};

/**
 * PlayerCreateRequest
 */
export type PlayerCreateRequest = {
  /**
   * Gender
   */
  gender: 'male' | 'female';
  /**
   * Name
   */
  name: string;
  /**
   * Sport Id
   */
  sport_id: number;
  /**
   * Team Ids
   */
  team_ids?: Array<number>;
};

/**
 * PlayerListResponse
 */
export type PlayerListResponse = {
  pagination: PlayerPaginationResponse;
  /**
   * Players
   */
  players: Array<PlayerResponse>;
};

/**
 * PlayerPaginationResponse
 */
export type PlayerPaginationResponse = {
  /**
   * Page
   */
  page: number;
  /**
   * Per Page
   */
  per_page: number;
  /**
   * Total Items
   */
  total_items: number;
  /**
   * Total Pages
   */
  total_pages: number;
};

/**
 * PlayerResponse
 */
export type PlayerResponse = {
  /**
   * Created At
   */
  created_at: string;
  /**
   * Disabled At
   */
  disabled_at: string | null;
  /**
   * Gender
   */
  gender: 'male' | 'female';
  /**
   * Id
   */
  id: number;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Name
   */
  name: string;
  sport: SportResponse;
  /**
   * Teams
   */
  teams: Array<PlayerTeamResponse>;
};

/**
 * PlayerTeamResponse
 */
export type PlayerTeamResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
};

/**
 * PlayerUpdateRequest
 */
export type PlayerUpdateRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Team Ids
   */
  team_ids: Array<number>;
};

/**
 * SignupRequest
 */
export type SignupRequest = {
  /**
   * Birthdate
   */
  birthdate: string;
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
};

/**
 * SignupResponse
 */
export type SignupResponse = {
  /**
   * Message
   */
  message: string;
  user: UserResponse;
};

/**
 * SportCreateRequest
 */
export type SportCreateRequest = {
  /**
   * Max Players
   */
  max_players: number;
  /**
   * Max Players In Game
   */
  max_players_in_game: number;
  /**
   * Name
   */
  name: string;
};

/**
 * SportEnvelope
 */
export type SportEnvelope = {
  sport: SportResponse;
};

/**
 * SportListResponse
 */
export type SportListResponse = {
  /**
   * Sports
   */
  sports: Array<SportResponse>;
};

/**
 * SportResponse
 */
export type SportResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Max Players
   */
  max_players: number;
  /**
   * Max Players In Game
   */
  max_players_in_game: number;
  /**
   * Name
   */
  name: string;
};

/**
 * SportUpdateRequest
 */
export type SportUpdateRequest = {
  /**
   * Max Players
   */
  readonly max_players?: number | null;
  /**
   * Max Players In Game
   */
  readonly max_players_in_game?: number | null;
  /**
   * Name
   */
  name: string;
};

/**
 * TeamCreateRequest
 */
export type TeamCreateRequest = {
  /**
   * Gender Category
   */
  gender_category: 'male' | 'female';
  /**
   * Name
   */
  name: string;
  /**
   * Sport Id
   */
  sport_id: number;
};

/**
 * TeamEnvelope
 */
export type TeamEnvelope = {
  team: TeamResponse;
};

/**
 * TeamListResponse
 */
export type TeamListResponse = {
  pagination: PaginationResponse;
  /**
   * Teams
   */
  teams: Array<TeamResponse>;
};

/**
 * TeamResponse
 */
export type TeamResponse = {
  /**
   * Created At
   */
  created_at: string;
  /**
   * Disabled At
   */
  disabled_at: string | null;
  /**
   * Gender Category
   */
  gender_category: 'male' | 'female';
  /**
   * Id
   */
  id: number;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Name
   */
  name: string;
  sport: SportResponse;
};

/**
 * TeamUpdateRequest
 */
export type TeamUpdateRequest = {
  /**
   * Name
   */
  name: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
  /**
   * Access Expires In
   */
  access_expires_in: number;
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Refresh Token
   */
  refresh_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * UserEnvelope
 */
export type UserEnvelope = {
  user: UserResponse;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Birthdate
   */
  birthdate: string;
  /**
   * Creation Date
   */
  creation_date: string | null;
  /**
   * Email
   */
  email: string;
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Role
   */
  role: string;
};

/**
 * ValidationDetail
 */
export type ValidationDetail = {
  /**
   * Field
   */
  field: string;
  /**
   * Message
   */
  message: string;
  /**
   * Type
   */
  type: string;
};

/**
 * ValidationErrorModel
 */
export type ValidationErrorModel = {
  /**
   * Error context
   *
   * An optional object which contains values required to render the error message.
   */
  ctx?: {
    [key: string]: unknown;
  } | null;
  /**
   * Input
   *
   * The input provided for validation.
   */
  input: unknown;
  /**
   * Location
   *
   * The error's location as a list.
   */
  loc: Array<unknown>;
  /**
   * Message
   *
   * A human readable explanation of the error.
   */
  msg: string;
  /**
   * Error Type
   *
   * A computer-readable identifier of the error type.
   */
  type: string;
  /**
   * URL
   *
   * The URL to further information about the error.
   */
  url?: string | null;
};

/**
 * LoginRequest
 */
export type LoginRequestWritable = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * SignupRequest
 */
export type SignupRequestWritable = {
  /**
   * Birthdate
   */
  birthdate: string;
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
  /**
   * Password
   */
  password: string;
};

/**
 * SportUpdateRequest
 */
export type SportUpdateRequestWritable = {
  /**
   * Name
   */
  name: string;
};

export type AuthLoginData = {
  body: LoginRequestWritable;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type AuthLoginErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
  /**
   * OK
   */
  200: TokenResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/logout';
};

export type AuthLogoutErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type AuthLogoutError = AuthLogoutErrors[keyof AuthLogoutErrors];

export type AuthLogoutResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/me';
};

export type AuthMeErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type AuthMeError = AuthMeErrors[keyof AuthMeErrors];

export type AuthMeResponses = {
  /**
   * OK
   */
  200: UserEnvelope;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthRefreshData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/refresh';
};

export type AuthRefreshErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type AuthRefreshError = AuthRefreshErrors[keyof AuthRefreshErrors];

export type AuthRefreshResponses = {
  /**
   * OK
   */
  200: TokenResponse;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type AuthSignupData = {
  body: SignupRequestWritable;
  path?: never;
  query?: never;
  url: '/auth/signup';
};

export type AuthSignupErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Conflict
   */
  409: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type AuthSignupError = AuthSignupErrors[keyof AuthSignupErrors];

export type AuthSignupResponses = {
  /**
   * Created
   */
  201: SignupResponse;
};

export type AuthSignupResponse = AuthSignupResponses[keyof AuthSignupResponses];

export type PlayersListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Search
     *
     * Partial accent-insensitive Player-name search.
     */
    search?: string | null;
    /**
     * Sport Id
     */
    sport_id?: number | null;
    /**
     * Gender
     */
    gender?: 'male' | 'female' | null;
    /**
     * Team Id
     */
    team_id?: number | null;
    /**
     * Status
     */
    status?: 'enabled' | 'disabled' | 'all';
    /**
     * Sort
     */
    sort?: 'name_asc' | 'created_at_desc';
    /**
     * Page
     */
    page?: number;
  };
  url: '/players';
};

export type PlayersListErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type PlayersListError = PlayersListErrors[keyof PlayersListErrors];

export type PlayersListResponses = {
  /**
   * OK
   */
  200: PlayerListResponse;
};

export type PlayersListResponse = PlayersListResponses[keyof PlayersListResponses];

export type PlayersCreateData = {
  body: PlayerCreateRequest;
  path?: never;
  query?: never;
  url: '/players';
};

export type PlayersCreateErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Conflict
   */
  409: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type PlayersCreateError = PlayersCreateErrors[keyof PlayersCreateErrors];

export type PlayersCreateResponses = {
  /**
   * Created
   */
  201: PlayerResponse;
};

export type PlayersCreateResponse = PlayersCreateResponses[keyof PlayersCreateResponses];

export type PlayersGetData = {
  body?: never;
  path: {
    /**
     * Player Id
     */
    player_id: number;
  };
  query?: never;
  url: '/players/{player_id}';
};

export type PlayersGetErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type PlayersGetError = PlayersGetErrors[keyof PlayersGetErrors];

export type PlayersGetResponses = {
  /**
   * OK
   */
  200: PlayerResponse;
};

export type PlayersGetResponse = PlayersGetResponses[keyof PlayersGetResponses];

export type PlayersUpdateData = {
  body: PlayerUpdateRequest;
  path: {
    /**
     * Player Id
     */
    player_id: number;
  };
  query?: never;
  url: '/players/{player_id}';
};

export type PlayersUpdateErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Conflict
   */
  409: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type PlayersUpdateError = PlayersUpdateErrors[keyof PlayersUpdateErrors];

export type PlayersUpdateResponses = {
  /**
   * OK
   */
  200: PlayerResponse;
};

export type PlayersUpdateResponse = PlayersUpdateResponses[keyof PlayersUpdateResponses];

export type PlayersDisableData = {
  body?: never;
  path: {
    /**
     * Player Id
     */
    player_id: number;
  };
  query?: never;
  url: '/players/{player_id}/disable';
};

export type PlayersDisableErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type PlayersDisableError = PlayersDisableErrors[keyof PlayersDisableErrors];

export type PlayersDisableResponses = {
  /**
   * OK
   */
  200: PlayerResponse;
};

export type PlayersDisableResponse = PlayersDisableResponses[keyof PlayersDisableResponses];

export type PlayersEnableData = {
  body?: never;
  path: {
    /**
     * Player Id
     */
    player_id: number;
  };
  query?: never;
  url: '/players/{player_id}/enable';
};

export type PlayersEnableErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type PlayersEnableError = PlayersEnableErrors[keyof PlayersEnableErrors];

export type PlayersEnableResponses = {
  /**
   * OK
   */
  200: PlayerResponse;
};

export type PlayersEnableResponse = PlayersEnableResponses[keyof PlayersEnableResponses];

export type SportsListData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/sports';
};

export type SportsListErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type SportsListError = SportsListErrors[keyof SportsListErrors];

export type SportsListResponses = {
  /**
   * OK
   */
  200: SportListResponse;
};

export type SportsListResponse = SportsListResponses[keyof SportsListResponses];

export type SportsCreateData = {
  body: SportCreateRequest;
  path?: never;
  query?: never;
  url: '/sports';
};

export type SportsCreateErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Conflict
   */
  409: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type SportsCreateError = SportsCreateErrors[keyof SportsCreateErrors];

export type SportsCreateResponses = {
  /**
   * Created
   */
  201: SportEnvelope;
};

export type SportsCreateResponse = SportsCreateResponses[keyof SportsCreateResponses];

export type SportsDeleteData = {
  body?: never;
  path: {
    /**
     * Sport Id
     */
    sport_id: number;
  };
  query?: never;
  url: '/sports/{sport_id}';
};

export type SportsDeleteErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Conflict
   */
  409: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type SportsDeleteError = SportsDeleteErrors[keyof SportsDeleteErrors];

export type SportsDeleteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type SportsDeleteResponse = SportsDeleteResponses[keyof SportsDeleteResponses];

export type SportsGetData = {
  body?: never;
  path: {
    /**
     * Sport Id
     */
    sport_id: number;
  };
  query?: never;
  url: '/sports/{sport_id}';
};

export type SportsGetErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type SportsGetError = SportsGetErrors[keyof SportsGetErrors];

export type SportsGetResponses = {
  /**
   * OK
   */
  200: SportEnvelope;
};

export type SportsGetResponse = SportsGetResponses[keyof SportsGetResponses];

export type SportsUpdateData = {
  body: SportUpdateRequestWritable;
  path: {
    /**
     * Sport Id
     */
    sport_id: number;
  };
  query?: never;
  url: '/sports/{sport_id}';
};

export type SportsUpdateErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Conflict
   */
  409: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type SportsUpdateError = SportsUpdateErrors[keyof SportsUpdateErrors];

export type SportsUpdateResponses = {
  /**
   * OK
   */
  200: SportEnvelope;
};

export type SportsUpdateResponse = SportsUpdateResponses[keyof SportsUpdateResponses];

export type TeamsListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Search
     *
     * Partial accent-insensitive Team-name search.
     */
    search?: string | null;
    /**
     * Sport Id
     */
    sport_id?: number | null;
    /**
     * Gender Category
     */
    gender_category?: 'male' | 'female' | null;
    /**
     * Status
     */
    status?: 'enabled' | 'disabled' | 'all';
    /**
     * Sort
     */
    sort?: 'name_asc' | 'created_at_desc';
    /**
     * Page
     */
    page?: number;
  };
  url: '/teams';
};

export type TeamsListErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type TeamsListError = TeamsListErrors[keyof TeamsListErrors];

export type TeamsListResponses = {
  /**
   * OK
   */
  200: TeamListResponse;
};

export type TeamsListResponse = TeamsListResponses[keyof TeamsListResponses];

export type TeamsCreateData = {
  body: TeamCreateRequest;
  path?: never;
  query?: never;
  url: '/teams';
};

export type TeamsCreateErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Conflict
   */
  409: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type TeamsCreateError = TeamsCreateErrors[keyof TeamsCreateErrors];

export type TeamsCreateResponses = {
  /**
   * Created
   */
  201: TeamEnvelope;
};

export type TeamsCreateResponse = TeamsCreateResponses[keyof TeamsCreateResponses];

export type TeamsGetData = {
  body?: never;
  path: {
    /**
     * Team Id
     */
    team_id: number;
  };
  query?: never;
  url: '/teams/{team_id}';
};

export type TeamsGetErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type TeamsGetError = TeamsGetErrors[keyof TeamsGetErrors];

export type TeamsGetResponses = {
  /**
   * OK
   */
  200: TeamEnvelope;
};

export type TeamsGetResponse = TeamsGetResponses[keyof TeamsGetResponses];

export type TeamsUpdateData = {
  body: TeamUpdateRequest;
  path: {
    /**
     * Team Id
     */
    team_id: number;
  };
  query?: never;
  url: '/teams/{team_id}';
};

export type TeamsUpdateErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Conflict
   */
  409: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type TeamsUpdateError = TeamsUpdateErrors[keyof TeamsUpdateErrors];

export type TeamsUpdateResponses = {
  /**
   * OK
   */
  200: TeamEnvelope;
};

export type TeamsUpdateResponse = TeamsUpdateResponses[keyof TeamsUpdateResponses];

export type TeamsDisableData = {
  body?: never;
  path: {
    /**
     * Team Id
     */
    team_id: number;
  };
  query?: never;
  url: '/teams/{team_id}/disable';
};

export type TeamsDisableErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type TeamsDisableError = TeamsDisableErrors[keyof TeamsDisableErrors];

export type TeamsDisableResponses = {
  /**
   * OK
   */
  200: TeamEnvelope;
};

export type TeamsDisableResponse = TeamsDisableResponses[keyof TeamsDisableResponses];

export type TeamsEnableData = {
  body?: never;
  path: {
    /**
     * Team Id
     */
    team_id: number;
  };
  query?: never;
  url: '/teams/{team_id}/enable';
};

export type TeamsEnableErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Unprocessable Entity
   */
  422: ErrorResponse;
  /**
   * Service Unavailable
   */
  503: ErrorResponse;
};

export type TeamsEnableError = TeamsEnableErrors[keyof TeamsEnableErrors];

export type TeamsEnableResponses = {
  /**
   * OK
   */
  200: TeamEnvelope;
};

export type TeamsEnableResponse = TeamsEnableResponses[keyof TeamsEnableResponses];
